name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 black
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Format check with black
      run: black --check --diff .
    
    - name: Test script syntax
      run: python -m py_compile drugs_classify.py
    
    - name: Create test data
      run: |
        mkdir -p unclassified_drugs
        echo "id,name,short_composition1,short_composition2" > unclassified_drugs/test_data.csv
        echo "1,Test Drug,amoxicillin,paracetamol" >> unclassified_drugs/test_data.csv
    
    - name: Run classification test
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from drugs_classify import classify_row_text
        result = classify_row_text('amoxicillin paracetamol')
        assert 'Antibiotics' in result
        print('Classification test passed')
        "