name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety pylint
        pip install -r requirements.txt
    
    - name: Security check with bandit
      run: bandit -r . -f json -o bandit-report.json || true
    
    - name: Safety check for vulnerabilities
      run: safety check --json --output safety-report.json || true
    
    - name: Code analysis with pylint
      run: pylint drugs_classify.py --output-format=json > pylint-report.json || true
    
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: code-quality-reports
        path: |
          bandit-report.json
          safety-report.json
          pylint-report.json