name: Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create release package
      run: |
        mkdir -p release
        cp drugs_classify.py release/
        cp requirements.txt release/
        cp -r unclassified_drugs release/ || echo "No input data to copy"
        tar -czf mediwise-drug-classification.tar.gz release/
    
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v3
      with:
        name: mediwise-drug-classification
        path: mediwise-drug-classification.tar.gz